#!/bin/bash

#ocdp = One Click Deleven Pi

#This command makes, that if there is an error, it stops
set -e


#Functions:

apps()	{
	echo "Installing your chosen Apps..."
	sudo apt install screen -y
	sudo apt install mosh -y
	sudo apt install neofetch -y
	sudo apt install timeshift -y
	sudo apt install nautilus -y
	sudo apt install openjdk-11-jre-headless -y
	sudo apt install samba samba-common-bin -y
	sudo apt install glances -y
	sudo apt install tightvncserver -y
	sudo apt install git -y
	sudo apt install wget -y
	sudo apt install rsync -y
	sudo apt install gnome-disk-utility -y
}

clean()	{
	echo "cleaning up..."
	sudo apt autoremove -yy
	sudo apt autoclean
}

delevenhelp() {
	cat << EOF
--help										this command
--clean

--mc-install-startscript					creates/overwrites /home/pi/Minecraft/start.sh
--mc-start									starts Minecraftserver in a Screen
											Screen Commands:
											screen -ls = List screens to see if one is running
											screen -r = go to screen, if there are mor the one use screen -r screenname (7094.Minecraft for example)
											kill 7094 = kills the screen with the ID 7094
											exit the screen with 'ctrl+a then d'


EOF
}

directories()	{
	echo "creating needed directories..."
	sudo mkdir /home/pi/bin
	sudo mkdir /home/pi/Minecraft
	sudo mkdir /home/pi/NAS
}

docker()	{
	echo "getting rid of old docker installs and install current version..."
	sudo apt-get remove docker docker-engine docker.io
	sudo curl -fsSL https://get.docker.com -o get-docker.sh
	sudo sh get-docker.sh
#Portainer gets installed as well
	echo "installing Portainer..."
	sudo docker volume create portainer_data
	sudo docker run -d -p 9000:9000 -p 8000:8000 --name portainer --$
	sudo docker ps	
}

leave() {
	echo "--------------------------------------"
	echo " Whatever you decided to to, its done "
	echo "--------------------------------------"
	exit
}

minecraft-install-startscript()	{
	echo "installing the Minecraft Server Startscript in /home/pi/Minecraft..."
	cat > /home/pi/Minecraft/start.sh << EOF
	cd /home/pi/Minecraft
	java -Xms2G -Xmx6G -jar paper-79.jar --nogui

	# substitute paper-79.jar with the version of minecraftserver .jar you want to run
	# I get mine from https://papermc.io/downloads
EOF
	chmod +x /home/pi/Minecraft/start.sh
	}

minecraft-server-start()	{
	echo "starting the Minecraft Server..."
	screen -d -m -S Minecraft bash -c '/home/pi/Minecraft/start.sh'
}

readme()	{
cat << EOF
 -------------------------------------------------------------------------------------------------
ooooooooo.   oooooooooooo       .o.       oooooooooo.   ooo        ooooo oooooooooooo 
`888   `Y88. `888'     `8      .888.      `888'   `Y8b  `88.       .888' `888'     `8 
 888   .d88'  888             .8"888.      888      888  888b     d'888   888         
 888ooo88P'   888oooo8       .8' `888.     888      888  8 Y88. .P  888   888oooo8    
 888`88b.     888    "      .88ooo8888.    888      888  8  `888'   888   888    "    
 888  `88b.   888       o  .8'     `888.   888     d88'  8    Y     888   888       o 
 o888o  o888o o888ooooood8 o88o     o8888o o888bood8P'   o8o        o888o o888ooooood8  
--------------------------------------------------------------------------------------------------
                       _       _     
  ___ _ __ ___  _ __  (_) ___ | |__  
 / __| '__/ _ \| '_ \ | |/ _ \| '_ \ 
| (__| | | (_) | | | || | (_) | |_) |
 \___|_|  \___/|_| |_|/ |\___/|_.__/ 
                    |__/          

add Cronjobs with "cronjob -e" current Version is found on 
https://github.com/GSB-Deleven/DelevenPi4/ 
see
DelevenPi4/crontab -e
DelevenPi4/bin/cronjobs
 
 __   ___  _  ___ 
 \ \ / / \| |/ __|
  \ V /| .` | (__ 
   \_/ |_|\_|\___|
                    
Startet tightVNCserver manuell mit tightvncserver -geometry 1920x1080


███████╗███╗   ██╗     ██╗ ██████╗ ██╗   ██╗                                          
██╔════╝████╗  ██║     ██║██╔═══██╗╚██╗ ██╔╝                                          
█████╗  ██╔██╗ ██║     ██║██║   ██║ ╚████╔╝                                           
██╔══╝  ██║╚██╗██║██   ██║██║   ██║  ╚██╔╝                                            
███████╗██║ ╚████║╚█████╔╝╚██████╔╝   ██║                                             
╚══════╝╚═╝  ╚═══╝ ╚════╝  ╚═════╝    ╚═╝                                             
                                                                                      
██████╗ ███████╗██╗     ███████╗██╗   ██╗███████╗███╗   ██╗    ██████╗ ██╗    ██╗  ██╗
██╔══██╗██╔════╝██║     ██╔════╝██║   ██║██╔════╝████╗  ██║    ██╔══██╗██║    ██║  ██║
██║  ██║█████╗  ██║     █████╗  ██║   ██║█████╗  ██╔██╗ ██║    ██████╔╝██║    ███████║
██║  ██║██╔══╝  ██║     ██╔══╝  ╚██╗ ██╔╝██╔══╝  ██║╚██╗██║    ██╔═══╝ ██║    ╚════██║
██████╔╝███████╗███████╗███████╗ ╚████╔╝ ███████╗██║ ╚████║    ██║     ██║         ██║
╚═════╝ ╚══════╝╚══════╝╚══════╝  ╚═══╝  ╚══════╝╚═╝  ╚═══╝    ╚═╝     ╚═╝         ╚═╝                                                                                 

EOF

}

update()	{
	echo "Starting Full system update"
	sudo apt update
	sudo apt full-upgrade -yy
}

#Executions:

if 	[ "$1" == "--clean" ]; then
	update
	clean
	leave
fi

if 	[ "$1" == "--help" ]; then
	delevenhelp
	exit
fi

if 	[ "$1" == "--mc-install-startscript" ]; then
	minecraft-install-startscript
	leave
	exit
fi

if 	[ "$1" == "--mc-start" ]; then
	minecraft-server-start
	cat << EOF 
	---------------------------------------------------------------------------------------------------------
	Server should have started
	screen -ls = List screens to see if one is running
	screen -r = go to screen, if there are mor the one use screen -r screenname (7094.Minecraft for example)
	kill 7094 = kills the screen with the ID 7094
	exit the screen with 'ctrl+a then d'
	---------------------------------------------------------------------------------------------------------
EOF
	exit
fi

if 	[ -n "$1" ]; then
	echo "Error: Invalid argument. Try 'ocdp --help' for more info."
	exit
fi